version: '3.8'

services:
  web:
    build: .
    container_name: diary_app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=your_secret_key_here  # В продакшн лучше использовать переменные окружения
    command: python run.py 